### ISSUE TITLE
Proposal: add ability to convert avsc to dataclasses

### ISSUE THREAD

**Issue by woile** [marcosschroh/dataclasses-avroschema#194]
## Proposal

Let user specify location of the schemas in `pyproject.toml` (maybe add support for another file like `.avro-schemas.toml`)

```toml
[tool.dataclasses-avroschema]
output_folder = "schemas"

[[tool.dataclasses-avroschema.schemas]]
source = "https://myschemas.org/example/1.1.1/hello.avsc"

[[tool.dataclasses-avroschema.schemas]]
source = "https://myschemas.org/org/schemas/example/hello.avsc"
output = "src/app/schemas/hello.py"
```

Having something like this would allow to keep track of which ones are used in git.

Then run `dc-avro transpile` (or something like that) and you'd get roughly:

```sh
app
├── schemas
│   └── example
│       └── 1_0_0
│           └── hello.py
└── src
    └── app
        └── schemas
            └── hello.py
```

## Developers workflow

Normally when working with avro you have a central registry with all the schemas. I think this package could be useful in 2 ways:

1. Generate schemas from your dataclasses. It is actually one of the best tools to create schemas ATM (Usually done by producers)
2. Generate dataclasses from a given schema (Useful for developers who have to consume)

This proposal would address point `2`.

## Notes

- This could be an `extra` in the package, requiring users to install like `pip install dataclasses-avroschema[cli]`
